import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
from app.domain.sales import Sale

class PDFService:
    @staticmethod
    def generate_invoice(sale: Sale) -> io.BytesIO:
        buffer = io.BytesIO()
        p = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Header
        p.setFont("Helvetica-Bold", 20)
        tenant_name = sale.tenant.name if sale.tenant else "NEXUS ERP"
        p.drawString(1 * inch, height - 0.8 * inch, tenant_name)
        
        p.setFont("Helvetica", 9)
        y_header = height - 1.0 * inch
        if sale.tenant and sale.tenant.tax_id:
            p.drawString(1 * inch, y_header, f"RIF/Tax ID: {sale.tenant.tax_id}")
            y_header -= 0.15 * inch
        if sale.tenant and sale.tenant.address:
            p.drawString(1 * inch, y_header, f"Address: {sale.tenant.address}")
            y_header -= 0.15 * inch
        if sale.tenant and sale.tenant.phone:
            p.drawString(1 * inch, y_header, f"Phone: {sale.tenant.phone}")
            y_header -= 0.15 * inch

        # Invoice Info (Right side)
        p.setFont("Helvetica-Bold", 12)
        p.drawRightString(7.5 * inch, height - 0.8 * inch, "INVOICE")
        p.setFont("Helvetica", 10)
        p.drawRightString(7.5 * inch, height - 1.0 * inch, f"No: {sale.id}")
        p.drawRightString(7.5 * inch, height - 1.2 * inch, f"Date: {sale.created_at.strftime('%Y-%m-%d')}")

        # Customer Info
        p.setFont("Helvetica-Bold", 12)
        p.drawString(1 * inch, height - 2.2 * inch, "Bill To:")
        p.setFont("Helvetica", 10)
        # Assuming we have customer name, if not use ID
        customer_name = getattr(sale.customer, 'name', f"Customer ID: {sale.customer_id}")
        p.drawString(1 * inch, height - 2.4 * inch, customer_name)

        # Table Header
        p.line(1 * inch, height - 2.8 * inch, 7.5 * inch, height - 2.8 * inch)
        p.setFont("Helvetica-Bold", 10)
        p.drawString(1 * inch, height - 3.0 * inch, "Description")
        p.drawString(4 * inch, height - 3.0 * inch, "Qty")
        p.drawString(5 * inch, height - 3.0 * inch, "Unit Price")
        p.drawString(6.5 * inch, height - 3.0 * inch, "Total")
        p.line(1 * inch, height - 3.1 * inch, 7.5 * inch, height - 3.1 * inch)

        # Table Content
        y = height - 3.3 * inch
        p.setFont("Helvetica", 10)
        for detail in sale.details:
            product_name = getattr(detail.product, 'name', f"Product {detail.product_id}")
            p.drawString(1 * inch, y, product_name)
            p.drawString(4 * inch, y, str(detail.quantity))
            p.drawString(5 * inch, y, f"${detail.unit_price:,.2f}")
            p.drawString(6.5 * inch, y, f"${detail.subtotal:,.2f}")
            y -= 0.2 * inch
            
            if y < 1 * inch: # Simple page break check
                p.showPage()
                y = height - 1 * inch

        # Totals
        p.line(5 * inch, y - 0.2 * inch, 7.5 * inch, y - 0.2 * inch)
        y -= 0.4 * inch
        p.setFont("Helvetica-Bold", 10)
        p.drawString(5 * inch, y, "Subtotal:")
        p.drawRightString(7.5 * inch, y, f"${sale.subtotal:,.2f}")
        
        y -= 0.2 * inch
        p.drawString(5 * inch, y, "Tax (16%):")
        p.drawRightString(7.5 * inch, y, f"${sale.tax_total:,.2f}")
        
        y -= 0.3 * inch
        p.setFont("Helvetica-Bold", 14)
        p.drawString(5 * inch, y, "TOTAL:")
        p.drawRightString(7.5 * inch, y, f"${sale.total:,.2f}")

        # Footer
        p.setFont("Helvetica-Oblique", 8)
        p.drawCentredString(width / 2, 0.5 * inch, "Thank you for your business! Generated by NEXUS ERP.")

        p.showPage()
        p.save()
        buffer.seek(0)
        return buffer
