"""Add type and number to debit_notes

Revision ID: ae45cd84a31c
Revises: 
Create Date: 2026-06-08 14:21:29.283915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae45cd84a31c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debit_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_debit_notes_number'), ['number'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_subtype'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_warehouse_id'))

    with op.batch_alter_table('system_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_system_movements_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_locked'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_locked'), ['is_locked'], unique=False)

    with op.batch_alter_table('system_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_movements_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_movements_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_subtype'), ['movement_subtype'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('debit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debit_notes_number'))
        batch_op.drop_column('type')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
